version: '3'

secrets:
  mongo-root-passwd:
    file: mongo/root-passwd
  mongo-user-passwd:
    file: mongo/user-passwd

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: boilerplatetheme_root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-passwd
      MONGO_INITDB_USERNAME: boilerplatetheme_service
      MONGO_INITDB_PASSWORD_FILE: /run/secrets/mongo-user-passwd
      MONGO_INITDB_DATABASE: boilerplatetheme
    volumes:
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    secrets:
      - mongo-root-passwd
      - mongo-user-passwd

  boilerplatetheme:
    image: boilerplatetheme
    build:
      context: .
      target: development
      args:
        NEXT_PUBLIC_ORIGIN: http://localhost:3000
    environment:
      PORT: 3000
      NEXT_PUBLIC_ORIGIN: http://localhost:3000
      MONGO_CONNECTION_STRING: mongodb://boilerplatetheme_service:user@mongo:27017/boilerplatetheme
      ACCESS_TOKEN_SECRET: XADnwvYUZkrgGw5nVRBPiF3OALM9lwLrTdT9Bhy/iU8=
      REFRESH_TOKEN_SECRET: nRN9j9rQzV/pXTnWXtM7C1MyG77y7JSqW+PWQoOaLgg=
    ports:
      - 3000:3000
      - 9229:9229
      - 9222:9222
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    secrets:
      - mongo-user-passwd
